# Neden NumPY (tek diyez)
## Bu bir alt başlıktır (iki diyez)

Markdown seçerek buraya stediğimiz açıklamları yazabiliriz ve derleme esnasında bir sıkıntı çıkmaz.

hücre içindeki tüm kesme yapıştırma işlemler,nde ctrl + x,y,v kullanırız
hücre dışımda  ctrl'ye gerek yok

iki kez ard arda d'ye basınca hücreyi siler

In [2]:
import numpy as np

In [3]:
a= np.array([1,2,3,4]) #integer bir numpy array tanımladık
b= np.array([2,3,4,5])
a*b

array([ 2,  6, 12, 20])

In [6]:
np.array([3.4,5,6,10.1], dtype = int)  # dtype ile listeye oluşturmasını istediğimiz tipi söyledik

array([ 3,  5,  6, 10])

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
np.full((2,4),3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3]])

In [13]:
np.arange(0,35,3) #sıfırdan 35'e kadar 3'er artan doğrusal dizi tanımlar


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33])

**array özellikleri** _yapısal özellikler
** -> bold _ -> italic yapıyor

* ndim : boyut sayısı
* shape: boyut bilgisi 
* size : toplam eleman sayısı
* dtype : array veri tipini gösterir

In [22]:
a=np.random.randint(10,size=10)
a

array([9, 6, 4, 1, 4, 8, 8, 9, 8, 1])

In [21]:
a.ndim

1

In [23]:
a.shape

(10,)

In [24]:
a.size

10

In [25]:
a.dtype

dtype('int32')

In [27]:
b = np.random.randint(10,size=(3,5))
b

array([[5, 4, 1, 6, 4],
       [1, 6, 5, 6, 7],
       [6, 0, 0, 4, 5]])

In [28]:
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)

2
(3, 5)
15
int32


* *Yeniden Şekillendirme (Reshaping)*

Var olan numpy arrayini yeniden şekillendiriyor

In [32]:
a=np.arange(1,10)
print(a)
print(a.shape)
print(a.ndim)
print(a.size)
b=a.reshape((3,3))
print(b.shape)
print(b.ndim)
print(b.size)
print(b)

[1 2 3 4 5 6 7 8 9]
(9,)
1
9
(3, 3)
2
9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
x=a
print(a.ndim) # a tek boyutlu bir array yani vektör
x=a.reshape((1,9))
print(x.ndim) # x ise iki boyutlu yani bir matris

1
2


* *Birleştirme Concatenation*

verilen arrayleri birleştirme işlemi yapar

In [2]:
import numpy as np

x= np.array([1,2,3])
y= np.array([4,5,6])

xy = np.concatenate([x,y])
xy2 = np.concatenate((x,y))

print(type(xy))
print(type(xy2))
print(xy)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[1 2 3 4 5 6]


* *2 Dimension Array Concatenation* 
* np.concanate([arrrays that will concanate], axis: which axis they will concanate based on)

axis is default 0

0 means that concanate operation will done based on rows

1 means concanate operation will done based on columns


In [13]:
xx = np.array([[1,2,3],[4,5,6]])
xx_based_on_rows = np.concatenate([xx,xx],axis=0)
print(xx_based_on_rows)
print("\n----------------------\n")
xx_based_on_columns = np.concatenate([xx,xx], axis=1)
print(xx_based_on_columns)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]

----------------------

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


* *İki boyutlu ayırma (vsplit/hsplit)*

In [17]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
# vsplit splits array vertical

ust,alt = np.vsplit(x, [2]) 
print(ust,"\n---------\n",alt)

[[0 1 2 3]
 [4 5 6 7]] 
---------
 [[ 8  9 10 11]
 [12 13 14 15]]


In [23]:
# hspilt splits array horizontal

sol, sag = np.hsplit(x,[2])
print(sol,"\n--------\n",sag)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 
--------
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


* *Sorting and* *2 Dimensional Sorting*

In [24]:
v = [1,4,45,12,1325,576]

np.sort(v) # np.sort() func does not change the array


array([   1,    4,   12,   45,  576, 1325])

In [26]:
v.sort() # sorts the array by  changing it's indexes
v

[1, 4, 12, 45, 576, 1325]

In [27]:
#iki boyutlu 

v = np.random.normal(20,5,(3,3)) # ortalaması 20 , standart sapması 5 olacak şekilde 3x3 lük bir matris oluşturur
v

array([[34.76850466, 16.27708282, 22.01643462],
       [13.64570968, 16.0231825 , 25.47862071],
       [14.62299401, 18.55670434, 25.6301174 ]])

In [28]:
# iki boyutluk arrayin satırlarını sıralamak istiyorsak (her bir satırı kendi içinde sıralar)
np.sort(v, axis=1)

array([[16.27708282, 22.01643462, 34.76850466],
       [13.64570968, 16.0231825 , 25.47862071],
       [14.62299401, 18.55670434, 25.6301174 ]])

In [30]:
#iki boyutlu arrayin sütunlarınısıralamak istiyorsak
np.sort(v, axis=0)

array([[13.64570968, 16.0231825 , 22.01643462],
       [14.62299401, 16.27708282, 25.47862071],
       [34.76850466, 18.55670434, 25.6301174 ]])

In [3]:
x = np.array([[[7,9],
     [4,0],
     [5,9]],
    [[4,8],
    [6,4],
    [4,5]],
    [[2,2],
    [8,2],
    [0,2]]])

print(x.ndim)
print(x.shape)
print(x.size)

3
(3, 3, 2)
18


* *Array Alt Küme İşlemleri (Slicing)*  



In [1]:
import numpy as np

In [12]:
# Tek Boyutlu arraylerde 
a = np.arange(1,10)
print(a)
print(a[0:3])
print(a[:3])
print(a[3:])
print(a[1:2])
print(a[1::2]) # birinci indeksten 2.'ye kadar indeksi 2 şer artarak yazdırır
print(a[0::3]) 

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[1 2 3]
[4 5 6 7 8 9]
[2]
[2 4 6 8]
[1 4 7]


In [14]:
#İki Boyutlu Arraylerde
m = np.random.randint(10, size=(5,5))
print(m)

[[1 6 8 8 3]
 [7 0 6 0 9]
 [2 1 4 7 9]
 [4 6 9 1 1]
 [6 2 5 5 0]]


In [20]:
print(m[:,:]) # tüm satır ve sğtunları döndürür
print("\n")
print(m[:,0]) # tüm satırlar 0. sütun
print("\n")
print(m[0,:]) # 0.satır tüm sütunlar

[[1 6 8 8 3]
 [7 0 6 0 9]
 [2 1 4 7 9]
 [4 6 9 1 1]
 [6 2 5 5 0]]


[1 7 2 4 6]


[1 6 8 8 3]


In [24]:
print(m[:,:])
print("\n")
print(m[1,:])
print("\n")
print(m[0:2,0:3]) #0'dan 2. satıra & 0'dan 3. sütuna
print("\n")
print(m[::, :2]) # tüm satırlar & 2. sütuna kadar
print("\n")
print(m[:,:2]) # tüm satırlar & 2. sütuna kadar
print("\n")
print(m[1:3,0:2])

[[1 6 8 8 3]
 [7 0 6 0 9]
 [2 1 4 7 9]
 [4 6 9 1 1]
 [6 2 5 5 0]]


[7 0 6 0 9]


[[1 6 8]
 [7 0 6]]


[[1 6]
 [7 0]
 [2 1]
 [4 6]
 [6 2]]


[[1 6]
 [7 0]
 [2 1]
 [4 6]
 [6 2]]


[[7 0]
 [2 1]]


* *Alt kümeler üzerinde işlem yapmak*

Normalde matrisler üzerinde işlem yaparken direkt olarak bir aralık seçip bu aralıığı bir değişkene atama yaparsak , ve daha sonra bu alt küme üzerinde değişiklik yaptığımızda ana matris üzerinde de bu değişimler gözleniyor.

Alt kümeyi ana matristen bağımsızlaştırmak için _copy_ metodunu kullanırız. BU metodla oluşturduğumuz alt küme ana matristen bağımsızldır, üzrinde istediğimiz gibi değişiklik yapabiliriz.

In [25]:
m = np.random.randint(10,size=(5,5))
m

array([[0, 1, 9, 3, 3],
       [7, 4, 5, 0, 6],
       [5, 7, 7, 4, 6],
       [2, 8, 8, 1, 1],
       [5, 3, 9, 5, 6]])

In [30]:
alt_a = m[0:3,2:5].copy()
alt_a

array([[9, 3, 3],
       [5, 0, 6],
       [7, 4, 6]])

In [32]:
alt_a[1,1]=1000001
alt_a

array([[      9,       3,       3],
       [      5, 1000001,       6],
       [      7,       4,       6]])

In [33]:
m

array([[0, 1, 9, 3, 3],
       [7, 4, 5, 0, 6],
       [5, 7, 7, 4, 6],
       [2, 8, 8, 1, 1],
       [5, 3, 9, 5, 6]])

### FANCY INDEX

* fancy index başka bir değişken(liste) vasıtası ile istenen indeksteki elemanın getirilmesidir. Kendine aşt bir fonksiyonu yoktur , indexlere erişim şeklimiz ile  fancy metodunu kullanmış oluruz.


In [35]:
# tek boyutlu arraylerde
v = np.arange(1,30,2)
v

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [40]:
al_getir=[1,3,5,14]  #tanımladığımız al_getir listesi içinde değerini görmek istediğimiz indexleri yazarız

v[1],v[3],v[5],v[14]

(3, 7, 11, 29)

In [41]:
v[al_getir] # tanımladığımız tek boyutlu array(vektör) içinde listedeki elemanları index olarak kabul edip bu indexlerin değerlerini döndürür

array([ 3,  7, 11, 29])

In [43]:
# iki byoyutlu arraylerde fancy
m = np.arange(9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
#seçeceğimiz satır ve sütunları ayrı listelerde tutarız
satir = np.array([0,1])
sutun = np.array([1,2]) 
m[satir,sutun]  # m[satir[0]sutun[0]} ve m[satir[1]sutun[1]] değerlerini döndürür

array([1, 5])

* Basit indeks & Fancy

İndekslere basitçe ulaşma ve fancy şekilde ulaşmayı aynı anda kullanabiliriz.

* Slice & Fancy

Slice ile fancy de birlikte kullanılabilir


In [48]:
m[2,[1,2]] #2. satıra basit indeksle(klasik indeks) , 1. ve 2. sütuna fancy indeksleme ile ulaştık

array([7, 8])

In [51]:
# slice ile fancy de bir arada kullanılabilir

m[1:2,[1,2]] #1. satırdan 2.'ye kadar & 1. ve 2. sütunu alır 

array([[4, 5]])

In [53]:
m[:3,[0,2]]

array([[0, 2],
       [3, 5],
       [6, 8]])

* _*Koşullu Eleman İşlemleri*_

İçindeki elemanları şartlara göre döndürür.

In [55]:
v = np.arange(1,6)
v

array([1, 2, 3, 4, 5])

In [57]:
v<3 # v içindeki değerlerin 5'ten büyük olup olmadığını kontrol eder true/false döndürür

array([ True,  True, False, False, False])

In [58]:
v[v<3] # v'nin içinde 3'ten küçük olan(true olan) değerleri döndürür

array([1, 2])

In [60]:
v[v>5] # v içinde 5'ten büyük eleman olmadığı için boş array döndürür

array([], dtype=int32)

In [66]:
v[v>=3]
v[v==2] #2 değeri varsa döndürür
v[v!=2] #2'ye eşit olmayanları döndürür
v[v==7] # 7 elemanı varsa döndürür yoksa boş array döner

array([], dtype=int32)

In [69]:
v*2 # çarpma işlemi yapar ama tekrar atama yapmadığımız sürece çarpılmış değerleri tutamayız
v

array([1, 2, 3, 4, 5])

In [70]:
v= v*3
v

array([ 3,  6,  9, 12, 15])

In [74]:
v/5
v*5/2
v**3 # küp alır

array([  27,  216,  729, 1728, 3375], dtype=int32)

### Matematiksel İşlemler (UFUNC)

biz vektörler üzerinde direkt olarak matematiksel işlemler yapıyoruz ama arka planda ufunc mekanizması çalışıyor,
bizim çarpma işlemi için kullandığımız yıldız(*) operatoru arka planda numpy fonksiyonları içinde dönüştürülüyor.  

In [97]:
v-1  #işlemi arka planda numpy.subtract(v,1) fonksiyonunu çağırıyor
v+1  #işlemi arka planda numpy.add(v,1) fonksiyonunu çağırıyor 
v*3  #işlemi arka planda numpy.multiply(v,3) fonksiyonunu çağırıyor
v/5  #işlemi arka planda numpy.divide(v,5) fonksiyonunu çağırıyor
v**2 #işlemi arka planda numpy.power(v,2) fonksiyonunu çağırıyor
v%2  #işlemi arka planda numpy.mod(v,2) fonksiyonunu çağırıyor

array([1, 0, 1, 0, 1], dtype=int32)

In [98]:
np.absolute(np.array([-3,-7,19,-11]))

array([ 3,  7, 19, 11])

In [100]:
# trigonometrik fonksiyonlar

np.sin(360)
np.cos(180)

-0.5984600690578581

In [104]:
#logaritma alma
#?np 
#numpy mathematics cheatsheet 

v= np.array([1,2,3])
np.log(v)
np.log2(v)
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

## Numpy ile İstatistik


'''
np.mean(arr,axis=0) | Returns mean along specific axis
np.sum() | Returns sum of arr 
np.min() | Returns minimum value of arr 
np.max(axis=0) | Returns maximum value of specific axis 
np.var(arr) | Returns the variance of array
np.std(arr,axis=1) | Returns the standard deviation of specific axis 
np.corrcoef() | Returns correlation coefficient of array
'''

In [107]:
v

array([1, 2, 3])

In [108]:
v.sum()

6

In [110]:
v.mean()

2.0

In [111]:
v.min()

1

In [112]:
v.std()

0.816496580927726

* *Numpy linalg k ile iki bilinmeyenli denklem çözümü*

5*x0 + x1 = 12
x0 + 3*x1 = 10

bilinmeyen ifadelerin katsayılarını bir vektöre, sonuçları da başka vektöre ekleriz


In [114]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [117]:
a


array([[5, 1],
       [1, 3]])

In [119]:
b

array([12, 10])

In [120]:
sonuc = np.linalg.solve(a,b)
sonuc

array([1.85714286, 2.71428571])

In [121]:
x = np.array([[4, 0, 3, 0, 1],

            [9, 6, 1, 5, 9],

            [1, 9, 0, 8, 2]])
x[0:1]

array([[4, 0, 3, 0, 1]])